apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-json
data:
  auth.json: |-
    {
        "valid_client_tokens": [
          "ba3069e9-d45d-4b28-add7-bd63f3e3d0b8",
          "9f0135c5-ec43-42c8-bfa7-40eeaf62ea83",
          "ddeb5c57-896b-47d4-b8ce-478ca1a71f05"
        ]
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2-proxy
  labels:
    app: app2-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2-proxy
  template:
    metadata:
      labels:
        app: app2-proxy
    spec:
      containers:
      - name: app2-proxy
        image: yurekten/taxii-proxy:latest
        imagePullPolicy: Always
        # command: ["/bin/bash", "-c", "sleep infinity"]
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: auth-json-volume
          subPath: auth.json
          mountPath: /app/auth.json
          readOnly: true
        env:
        - name: TAXII_SERVER_URL
          value: "http://kubernetes.docker.internal:32222"
        - name: COLLECTION_ID
          value: "vulnerabilities"
        - name: API_ROOT_NAME
          value: "app2"
        - name: MEDALLION_USERNAME
          value: "medallion_admin"
        - name: MEDALLION_USER_PASSWORD
          value: "Test.1234"
        - name: TAXII_PROXY_PORT
          value: "8080"
        - name: TAXII_PROXY_HOST
          value: "0.0.0.0"
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 10
      volumes:
      - name: auth-json-volume
        configMap:
          name: auth-json
---
apiVersion: v1
kind: Service
metadata:
  name: app2-proxy-service
  labels:
    app: app2-proxy
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: service-port
    nodePort: 32244
  selector:
    app: app2-proxy
  type: NodePort

