apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2-client
  labels:
    app: app2-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2-client
  template:
    metadata:
      labels:
        app: app2-client
    spec:
      containers:
      - name: app2-client
        image: yurekten/taxii-client:latest
        imagePullPolicy: Always
        env:
        - name: TAXII_SERVER_URL
          value: "http://kubernetes.docker.internal:32222"
        - name: COLLECTION_ID
          value: "vulnerabilities"
        - name: API_ROOT_NAME
          value: "app1"
        - name: MEDALLION_USERNAME
          value: "app2"
        - name: MEDALLION_USER_PASSWORD
          value: "Test.1234_app2"
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 10
