apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2-client
  labels:
    app: app2-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2-client
  template:
    metadata:
      labels:
        app: app2-client
    spec:
      containers:
      - name: app2-client
        image: yurekten/taxii-client:latest
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: taxii-client-envs
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 10
