apiVersion: apps/v1
kind: Deployment
metadata:
  name: taxii-server
  labels:
    app: taxii-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taxii-server
  template:
    metadata:
      labels:
        app: taxii-server
    spec:
      containers:
      - name: taxii-server
        image: yurekten/medallion:latest
        imagePullPolicy: Always
        # command: ["/bin/bash", "-c", "sleep infinity"]
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: medallion-init-envs
        volumeMounts:
        - name: medallion-config-json-volume
          subPath: medallion-config.json
          mountPath: /app/medallion_config.json
          readOnly: true
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 10
      initContainers:
      - name: wait-for-mongo
        image: busybox:latest
        envFrom:
        - secretRef:
            name: medallion-init-envs
        command: ['sh', '-c', 'until nc -z $(MONGODB_HOST) $(MONGODB_PORT); do echo waiting for mongo; sleep 5; done;']
      volumes:
      - name: medallion-config-json-volume
        secret:
          secretName: medallion-config-json
---
apiVersion: v1
kind: Service
metadata:
  name: taxii-server-service
  labels:
    app: taxii-server
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: service-port
    nodePort: 32222
  selector:
    app: taxii-server
  type: NodePort

