apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-proxy
  labels:
    app: app1-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1-proxy
  template:
    metadata:
      labels:
        app: app1-proxy
    spec:
      containers:
      - name: app1-proxy
        image: yurekten/taxii-proxy:latest
        imagePullPolicy: Always
        # command: ["/bin/bash", "-c", "sleep infinity"]
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: auth-json-volume
          subPath: taxii-proxy-auth.json
          mountPath: /app/taxii-proxy-auth.json
          readOnly: true
        envFrom:
        - secretRef:
            name: taxii-proxy-envs
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 10
      volumes:
      - name: auth-json-volume
        secret:
          secretName: taxii-proxy-auth-json
---
apiVersion: v1
kind: Service
metadata:
  name: app1-proxy-service
  labels:
    app: app1-proxy
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: service-port
    nodePort: 32233
  selector:
    app: app1-proxy
  type: NodePort

